# Generated by Django 5.0.6 on 2024-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajaxx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.TextField()),
            ],
        ),
    ]
