# Generated by Django 5.0.6 on 2024-07-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_ajaxx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajaxx',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
